### ISSUE TITLE
Review initial CODEOWNERS and MAINTAINERS.md

### ISSUE THREAD

**Issue by hdamker** [camaraproject/DeviceQualityIndicator#3]
**Problem description**

The PRs #1 and #2 are created based on the existing email communication in context of API Backlog.

**Expected action**

PRs got reviewed, potentially extended and merged after approvals.

**Additional context**

**Comment by akoshunyadi** [comment]
@hdamker can this issue be closed?

**Comment by hdamker** [comment]
> @hdamker can this issue be closed?

Yes, both PRs are merged already.
